### ISSUE TITLE
KML Coordinates Are Backward

### ISSUE THREAD

**Issue by riggsd** [masneyb/cavedbmanager#1]
The produced .KML files plot West Virginia caves in Antarctica because longitude and latitude are switched.

![screenshot 2017-04-15 18 07 14](https://cloud.githubusercontent.com/assets/647785/25067908/68d2b97c-2206-11e7-80e7-f10e1c4ca607.png)

Also, Google Earth complains about a parsing error when encountering `<br/>` tags in the KML because they're not namespaced or [surrounded by CDATA elements](https://developers.google.com/kml/documentation/kml_tut#descriptive_html).

Also also, we should **consider** switching the encoding to UTF-8 (not US-ASCII) since that's what Django natively streams in and out.

**Comment by riggsd** [comment]
I'll leave the file encoding question up to you!

**Comment by masneyb** [comment]
Thanks for the patches. I updated the encodings of the generated KML and GPX files to UTF-8 since that is what Python 3 now uses.

Brian
